# **Linear Algebra for CpE**

**Laboratory 6 :Matrices**

# **Activity**

**Task 1**

Create a function named mat_desc() that througouhly describes a matrix, it should:

1. Displays the shape, size, and rank of the matrix.
2. Displays whether the matrix is square or non-square.
3. Displays whether the matrix is an empty matrix.
4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np
def mat_desc(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nSize:\t{np.product(matrix.shape)}:\t\nRank:\t{matrix.ndim}\n')
  if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False
        is_identity = True if matrix.shape[0] == matrix.shape[1] and np.allclose(matrix, np.identity(matrix.shape[0])) else False
        is_zero = True if np.all((matrix == 0)) else False
        is_ones = True if np.all((matrix == 1)) else False

        print(f'is ones?: {is_ones}\n'f'is zero?: {is_zero}\n'f'is square?: {is_square}\n'f'is identity?: {is_identity}\n\n'
        )
        
  else:
        print('Matrix is Empty')

A = np.array([
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
])
B = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 1]
])
C = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [1, 0, 1]
])
D = np.array([
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
])
E = np.array([
    [],
    [],
    []
])
print("Matrix 1:")
mat_desc(A)
print("Matrix 2:")
mat_desc(B)
print("Matrix 3:")
mat_desc(C)
print("Matrix 4:")
mat_desc(D)
print("Matrix 5:")
mat_desc(E)        

  

Matrix 1:
Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Shape:	(3, 3)
Size:	9:	
Rank:	2

is ones?: False
is zero?: True
is square?: True
is identity?: False


Matrix 2:
Matrix:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Shape:	(3, 3)
Size:	9:	
Rank:	2

is ones?: True
is zero?: False
is square?: True
is identity?: False


Matrix 3:
Matrix:
[[1 0 1]
 [0 1 0]
 [1 0 1]]

Shape:	(3, 3)
Size:	9:	
Rank:	2

is ones?: False
is zero?: False
is square?: True
is identity?: False


Matrix 4:
Matrix:
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Shape:	(3, 4)
Size:	12:	
Rank:	2

is ones?: True
is zero?: False
is square?: False
is identity?: False


Matrix 5:
Matrix:
[]

Shape:	(3, 0)
Size:	0:	
Rank:	2

Matrix is Empty


**Task 2**

Create a function named mat_operations() that takes in two matrices or scalars a input parameters it should:

1.Display the description of each matrix, if the parameter is a scalar it tells that it is a scalar rather than describing it as a matrix.

2.Determines if the matrices are viable for operation and returns your own error message if they are not viable.

3.Returns the sum of the matrices.

4.Returns the difference of the matrices.

5.Returns the element-wise multiplication of the matrices.

6.Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than $(3,3)$. In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [9]:
def mat_operations(A,B):
    alpha = 10**-10
    
    if np.isscalar(A):
        print("Parameter 1 is scalar")
    else:
        print(f'Matrix 1:\n {A}\n\n'f'Matrix 1 Shape: {A.shape}\n'f'Matrix 1 Size: {np.product(A.shape)}\n' f'Matrix 1 Rank: {A.ndim}')
        if A.size > 0:
            is_ones = True if np.all((A == 1)) else False 
            is_zero = True if np.all((A == 0)) else False
            is_square = True if A.shape[0] == A.shape[1] else False
            is_identity = True if A.shape[0] == A.shape[1] and np.allclose(A, np.identity(A.shape[0])) else False
            print(f'is ones?: {is_ones}\n'f'is zero?: {is_zero}\n'f'is square?: {is_square}\n'f'is identity?: {is_identity}\n\n'
            )
        else:
            print("Matrix is Empty")
            
    if np.isscalar(B):
        print("Parameter 2 is scalar")
    else:
        print(f'Matrix 2:\n {B}\n\n'f'Matrix 2 Shape: {B.shape}\n'f'Matrix 2 Size: {np.product(B.shape)}\n'f'Matrix 2 Rank: {B.ndim}')
        if B.size > 0:
            is_ones = True if np.all((B == 1)) else False 
            is_zero = True if np.all((B == 0)) else False 
            is_square = True if B.shape[0] == B.shape[1] else False
            is_identity = True if B.shape[0] == B.shape[1] and np.allclose(B, np.identity(B.shape[0])) else False
            print(f'is ones?: {is_ones}\n'f'is zero?: {is_zero}\n'f'is square?: {is_square}\n'f'is identity?: {is_identity}\n\n')
        else:
            print("Matrix is Empty")
            
    if np.isscalar(A) == False and np.isscalar(B) == False:
        if (A.shape == B.shape):
            print(f'The Sum of the Matrices: \n{np.sum(np.add(A,B))}\n'f'\nThe Difference of the Matrices: \n{np.diff(np.subtract(A,B))}\n'f'\nThe Element-wise Multiplication of the Matrices: \n{np.multiply(A,B)}\n'f'\nThe Element-wise Division of the Matrices: \n{np.divide(A,B+alpha)}\n')
        else:
            print("Matrices are not viable for operation")
    else:
        print("Parameters are not viable for matrix operation")

A = np.array([
    [8, 6, 1],
    [3, 9, 0],
    [4, -1, -5]
])
B = np.array([
    [-7, -9, -3],
    [-3, -4, 0],
    [9, 4, 3]
])

C = np.array([
    [5, 4, 3],
    [7, 7, 2],
    [4, 0, 9]
])

D =  np.array([
    [3, 5, 6],
    [9, 1, 7],
    [2, 5, 9]
])
E = np.array([
    []
])

print("Pair 1 of matrices:")
mat_operations(A,B)
print("Pair 2 of matrices:")
mat_operations(C,D)
print("Pair 3 of matrices:")
mat_operations(A,E)


Pair 1 of matrices:
Matrix 1:
 [[ 8  6  1]
 [ 3  9  0]
 [ 4 -1 -5]]

Matrix 1 Shape: (3, 3)
Matrix 1 Size: 9
Matrix 1 Rank: 2
is ones?: False
is zero?: False
is square?: True
is identity?: False


Matrix 2:
 [[-7 -9 -3]
 [-3 -4  0]
 [ 9  4  3]]

Matrix 2 Shape: (3, 3)
Matrix 2 Size: 9
Matrix 2 Rank: 2
is ones?: False
is zero?: False
is square?: True
is identity?: False


The Sum of the Matrices: 
15

The Difference of the Matrices: 
[[  0 -11]
 [  7 -13]
 [  0  -3]]

The Element-wise Multiplication of the Matrices: 
[[-56 -54  -3]
 [ -9 -36   0]
 [ 36  -4 -15]]

The Element-wise Division of the Matrices: 
[[-1.14285714 -0.66666667 -0.33333333]
 [-1.         -2.25        0.        ]
 [ 0.44444444 -0.25       -1.66666667]]

Pair 2 of matrices:
Matrix 1:
 [[5 4 3]
 [7 7 2]
 [4 0 9]]

Matrix 1 Shape: (3, 3)
Matrix 1 Size: 9
Matrix 1 Rank: 2
is ones?: False
is zero?: False
is square?: True
is identity?: False


Matrix 2:
 [[3 5 6]
 [9 1 7]
 [2 5 9]]

Matrix 2 Shape: (3, 3)
Matrix 2 Size: 9
